export default {
  CHANGE_BASE_CURRENCY: 'CHANGE_BASE_CURRENCY',
  CHANGE_CURRENCY_AMOUNT: 'CHANGE_CURRENCY_AMOUNT',
  CHANGE_PRIMARY_COLOR: 'CHANGE_PRIMARY_COLOR',
  CHANGE_QUOTE_CURRENCY: 'CHANGE_QUOTE_CURRENCY',
  SWAP_CURRENCY: 'SWAP_CURRENCY',
  currencyType: {
    BASE_CURRENCY: 'BASE_CURRENCY',
    QUOTE_CURRENCY: 'QUOTE_CURRENCY',
  },
};
